### PR TITLE
Add instructions for extra ressources grants

### PR DESCRIPTION
**Pull request by guhur**

### CODE REVIEW

**Comment by remicres** [comment]
Thanks 👍
Maybe you can detail what "normal username" is ? I don't know this procedure. Is it $USER (the ones that runs passextranet)?

**Comment by lesteve** [comment]
I guess Jean-Zay username may be a bit clearer but yes it is the same `$USER` on a Jean-Zay login node.

I am guessing that WIP means that @guhur intends to add more details when he get the time :pray:.

Also this reminds me we should probably add how to access the extranet (or Jupyter notebooks launched by `idrlab`/`idrjup`) if you are trying to access it from somewhere else than an authorised machine: https://github.com/jean-zay-users/jean-zay-doc/issues/17

**Comment by guhur** [comment]
Work is ready for merging

**Comment by lesteve** [comment]
Thanks! Out of interest, did you manage to get a quota increase in the end?

**Comment by lesteve** [comment]
In an ideal world it would be good to tackle #17 for SOCKS proxy and then link to the doc, because not everyone knows this kind of tricks to access the extranet when not doing it from an authorised machine.

**Pull request merged**
