### PR TITLE
Contribution

### PR DESCRIPTION
**Pull request by remiDInria**
Hello,
Here is how i did to make gitlab-runner work on Jean Zay.
Hope it could be useful.

### CODE REVIEW

**Review by mdiazmel — COMMENTED** [review]
Hi @remiDInria ,

Thanks! This is a very nice trick! 

If I understood correctly, you have to launch your `tmux` session weekly, isn't ? (jobs in the master node are killed on Tuesdays, usually). Do you have an idea about how the time deducted from your project account? Just when the CI script triggers a job?

I'll merge this PR!

**Comment by remiDInria** [comment]
HI @mdiazmel,

Thanx for reviewing!

Yes, my tmux and screens are killed on Tuedays.
For time deduction, I can't be sure, but the gitlab-runner runs on front machines and time is not deducted on those.
Then your're right, depending on the CI job once triggered.

**Comment by mdiazmel** [comment]
@remiDInria,
Maybe, can you add a small warning at the beginning of the section, saying that people having access to the repository can potentially (and indirectly) use the hours of your project when using this setup ?
Thanks!

**Comment by lesteve** [comment]
Interesting! On top of Tuesdays maintenance (or login node restarts for other reasons) the 30-minute CPU time limit can also kill your gitlab runner

**Comment by mdiazmel** [comment]
Thanks a lot! Merging...

**Comment by remiDInria** [comment]
Thank a lot for merging!

**Pull request merged**
