### PR TITLE
Add some info about RSSI and idrquota

### PR DESCRIPTION
**Pull request by mypey**

### CODE REVIEW

**Comment by lesteve** [comment]
Hi @mypey, sorry I saw this PR just now, thanks a lot for this!

**Comment by lesteve** [comment]
I pushed some minor tweaks into your branch, merging thanks a lot!

**Comment by lesteve** [comment]
@mypey a few questions, if you have the time to answer them, it would be really appreciated:
- I was told by IDRIS that for CNRS people, the form about the "Responsable Sécurité Informatique" and the "Directeur de la structure de recherche" should be filled automatically. Was it not the case for you?
- did you actually ask for a WORK quota increase. How much did you ask for and was it easy to get or did you have to argue?

**Comment by mypey** [comment]
Hi @lesteve , I am a brand new research engineer in the support team at IDRIS (we met at the IPL Inria last week). I am very interested in your git doc! I am aware our full documentation might be laborious for a new user. We used to offer a "getting started" doc but it is not written yet for Jean Zay... We are late but we are working on it. In the meantime, I hope I can help here and give you some useful tips.

So I can't answer your first question but I can give you a very recent example for the second one: yesterday, a user asked us to increase his inodes quota from 1M to 3M in his $WORK. A small explanation is of course appreciated but I think it is just common sense. It is usually done in one line. If the user uses the spaces well, we approve his/her request right away and the new quota is available a couple of days later.

**Comment by lesteve** [comment]
> Hi @lesteve , I am a brand new research engineer in the support team at IDRIS (we met at the IPL Inria last week).

Right, your github handle now makes sense. Great to see you involved in this repo!

> We used to offer a "getting started" doc but it is not written yet for Jean Zay... We are late but we are working on it.

Nice to hear, let us know if you want feed-back before you put it online. Anyway we'll happily add a link to your "getting started" doc in this doc when it is online.

**Pull request merged**
