### PR TITLE
example scripts for LLM

### PR DESCRIPTION
**Pull request by cerisara**
Recent (2023) scripts for finetuning and inference of LLM on Jean Zay.
Recent (2024) scripts for pretraining an LLM on Jean Zay, either with DeepSpeed or Megatron-DS.

### CODE REVIEW

**Comment by lesteve** [comment]
Thanks for the PR! I guess originally the doc was intended to be stand-alone with some examples inside the repo, but I think it's fine to have external links like this one.

Apparently there was a readthedocs issue that I fixed. Can you push a commit into your branch to double-check the rendering of your PR?

**Comment by lesteve** [comment]
Hmmm maybe you need to merge `main` into your branch for the build to work properly? I don't know ...

**Comment by cerisara** [comment]
yes sorry, I forget the pull from upstream ;-) should work now...
Thanks !

**Comment by lesteve** [comment]
OK thanks for the PR (you got number #100 by the way :wink:)! I am going to merge this and probably reorder a bit afterwards, because this part is supposed to be about the content of the doc and there is a section which is more about external links.

**Pull request merged**
