### PR TITLE
Added procedure to add IP addresses to the original declaration

### LINKED ISSUE #33: Add procedure for how to add new IP addresses

### PR DESCRIPTION
**Pull request by oumayb**
@lesteve Fixes #33

### CODE REVIEW

**Comment by lesteve** [comment]
Thanks a lot for this! I added some small tweaks.

Can you confirm 3-4 days is once you send them the signed form?

**Comment by lesteve** [comment]
Also annoyingly "fixes issue #number" does not work (i.e. it does not close the issue automatically) you have to use "fix #number" ... I know easy to miss ...

For more details, look at [this](https://github.com/blog/1506-closing-issues-via-pull-requests).

**Comment by oumayb** [comment]
Actually 3-4 days was for the whole procedure. Once sent to gestutil@idris.fr it took around 24 hours.

**Comment by lesteve** [comment]
Also a nice tweak: you can link to a page of a pdf like this:
`http://www.idris.fr/media/data/formulaires/fgc.pdf#page=2`

Not very robust but still useful.

**Comment by oumayb** [comment]
Thanks!

**Comment by lesteve** [comment]
OK I corrected the 3-4 days thing. Anything else you see that could be improved, let me know (or fix it directly)!

If I don't hear anything, I'll merge this in one hour roughly.

**Comment by lesteve** [comment]
Merging, thanks a lot for the PR!

**Pull request merged**
