### PR TITLE
update about SSH connection to a compute node

### PR DESCRIPTION
**Pull request by mypey**

### CODE REVIEW

**Comment by lesteve** [comment]
Nice, thanks a lot!

By the way I asked a few months ago what happens if you have multiple jobs running on the same node, which job do you end up seeing when you `ssh` to the node. Do you happen to know the answer to this one?

**Comment by mypey** [comment]
Hi @lesteve,
once you are connected to a compute node, you can see any process running on it. So if you have four jobs running on the same node, you will see the four of them.

**Comment by lesteve** [comment]
But there is some kind of separation for GPUs right? I just tested with an interactive job and I see only one GPU inside the interactive job with `nvidia-smi` and only one when connecting to the node through `ssh`. 

Now my question was what happens if I have two jobs on the same node and I ssh to the node. Will I see two GPUs, will I see only one (which one in this case)?

**Comment by mypey** [comment]
You're right, sorry! I ran a test before answering but as I have some privileges as a member of the support team group, it was not relevant -_-'
We have to check once again in appropriate conditions. I'll come back to you.

**Comment by lesteve** [comment]
OK great, let me know!

**Comment by mypey** [comment]
Hi again,
the jobs are indeed separated in a way that prevents any overview of several jobs running on one node. It is related to cgroups management. We will send a reminder to the persons in charge of this issue.

**Comment by RemiLacroix-IDRIS** [comment]
Here is what currently happens:
 - a cgroup is created by Slurm for each jobs to ensure the allocated resources cannot be used by multiple users
 - when you do `ssh <node>`, there are some checks to ensure there is actually one of your jobs running on the node currently
 - if it is indeed the case, a new shell is created on the node and is attached to the cgroup of your job to ensure that you can see only the resources that have been allocated to you.

If you have multiple jobs running on node, it seems that the shell gets attached to the cgroup corresponding to the last job that have been allocated on the node, effectively preventing you from seeing the GPU allocated to your other jobs.

It is currently unclear if this behavior can be improved easily (i.e. is it possible to switch from one cgroup to another or to attach the shell to all cgroup).

**Comment by lesteve** [comment]
Thanks for the details!

I guess being able to specify which job (rather than which node) we want to connect to would be ideal, but as I understand it that may not be that easily feasible. To be fair, I think this is a bit of a edge case scenario, so for now I am going to add the caveat to the doc.

**Pull request merged**
