### PR TITLE
Add instructions about singularity

### PR DESCRIPTION
**Pull request by guhur**

### CODE REVIEW

**Comment by remicres** [comment]
Great one :+1: 

I believe that the docker -> singularity is possible in non root permissions with docker:
https://github.com/singularityhub/docker2singularity

**Comment by lesteve** [comment]
I think you can get a singularity image from a docker image with singularity, e.g. see the [official Jean-Zay doc](http://www.idris.fr/eng/jean-zay/cpu/jean-zay-utilisation-singularity-eng.html#building_an_image_from_a_repository)
```
singularity build image-singularity-tensorflow.sif docker://tensorflow/tensorflow:latest-gpu-py3
```

Personally, if I was trying to do it (disclaimer not tested, so there may be caveats):
- I would build a docker image on my laptop where I have all the rights I need
- build the singularity image from the docker image on my laptop
- copy the singularity image to Jean-Zay

**Comment by guhur** [comment]
Could you add it to the README? 

It did not fit my usecase, since no prebuilt docker could fit my need.

**Comment by lesteve** [comment]
> It did not fit my usecase, since no prebuilt docker could fit my need.

I think you can either:
- build your docker image locally, push your local docker image to dockerhub, use `docker pull`
- as an alternative apparently there is also a way to save the docker image to a tar and then build the singularity image from the .tar (Method 1 in https://www.nas.nasa.gov/hecc/support/kb/converting-docker-images-to-singularity-for-use-on-pleiades_643.html).

Whether it is better than converting the Dockerfile to singularity definition file, I am not too sure ... 

More a general thing I think it would be great to link singularity.md from the rest of the doc, e.g. tips-and-tricks.md so that it appears in the online doc. I think we should start splitting splitting tips-and-tricks.md into multiple pieces anyway. I'll try to look at this soonish.

Also completely unrelated, but I think Jean-Zay people would not be super happy about showing some paths structure so probably in your bind your should only use environment variables. Is that a problem in practice?

Same thing with SINGULARITY_ALLOWED_DIR, probably better not to show the full path, it should be defined when doing `module load singularity`. Does it not work for you?

**Comment by RemiLacroix-IDRIS** [comment]
It would indeed be best if you could avoid showing paths.

**Comment by guhur** [comment]
I updated the file with your comments

**Comment by lesteve** [comment]
Thanks a lot for this, I tweaked a few things, pushed into your branch, merging this one!

**Pull request merged**
