### PR TITLE
Put doc on readthedocs with mkdocs

### PR DESCRIPTION
**Pull request by mdiazmel**
This PR intends to create an static html version of this documentation and host it in readthedocs.

In order to do this:
- The structure of the docs was changed.
- An mkdocs.yml file was added to the root folder.
- A webhook was set up to build the docs at each push/PR.

[Final rendering is published (temporarily) here](https://jean-zay-doc--47.org.readthedocs.build/en/47/)

### CODE REVIEW

**Comment by lesteve** [comment]
Thanks for doing this, this looks very nice! I would be in favour of merging this one and iterate on it.

Out of curiosity, any particular reason you went for mkdocs rather than jupyter-book? One thing I saw that this was probably simpler to set up mkdocs with read the docs.

As our doc is quite simple I don't think this matters too much to be honest.

**Comment by mdiazmel** [comment]
> Out of curiosity, any particular reason you went for mkdocs rather than jupyter-book? One thing I saw that this was probably simpler to set up mkdocs with read the docs.

@lesteve, you're right, that was the main reason! Jupyter books are also nice but I don't think that we can propose interactive notebooks to be run easily in Jean Zay.  

I let you merge it!

**Comment by lesteve** [comment]
Great stuff, let's merge this one, thanks a lot @mdiazmel!

**Comment by lesteve** [comment]
And this is live on readthedocs: https://jean-zay-doc.readthedocs.io/en/latest/

**Pull request merged**
